# Metadata ----

### Project name: American Plaice Snapshot ESP 2026
### Code purpose: Indicator creation

### Author: Stephanie Owen
### Date started 09/09/2026

### Code reviewer:
### Date reviewed:

# Libraries & functions ----

# Data ----

## Commercial Data Pull using NEesp2::get_commercial_data ----
# Needs Oracle connection
# Output in '01_inputs/AMERICANPLAICE_Commercial_Indicators_Master.csv'
com_data <- NEesp2::get_commercial_data(
  ora_id = "user",
  oraprod_pw = "password",
  START.YEAR = 1996,
  END.YEAR = 2025,
  deflate_yr = 2025,
  spp_name = "AMERICANPLAICE",
  nespp3_codes = "('124')"
)

## Bottom temperature from Hubert (1959-2021) and GLORYS (2021-)
bt_hubert <- here::here("01_inputs/AMERICANPLAICE_hubert_bottomT.csv")
bt_glorys <- here::here("01_inputs/AMERICANPLAICE_glorys_bottomT.csv")

bt_data <- read.csv(bt_hubert) |>
  dplyr::bind_rows(read.csv(bt_glorys))

## Sea surface temperature ----
seasonal_sst <- read.csv(here::here('01_inputs/AMERICANPLAICE_sst.csv')) |>
  dplyr::filter(YEAR >= 1970) |>
  dplyr::filter(MONTH %in% 3:6) |>
  dplyr::group_by(YEAR) |>
  dplyr::summarize(DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE)) |>
  dplyr::mutate(INDICATOR_NAME = "seasonal_sst")

## Gulf Stream Index ----
gsi <- ecodata::gsi |>
  tidyr::separate(Time, c("Year", "Month"), sep = "\\.") |>
  dplyr::mutate(Month = dplyr::if_else(Month == "1", "10", Month)) |> # has october as '1' instead of '10'
  dplyr::filter(Var == 'gulf stream index', Year >= 1970) |>
  dplyr::rename(
    INDICATOR_NAME = Var,
    YEAR = Year,
    MONTH = Month,
    DATA_VALUE = Value
  ) |>
  dplyr::select(YEAR, MONTH, INDICATOR_NAME, DATA_VALUE) |>
  dplyr::mutate(YEAR = as.numeric(.data$YEAR)) |>
  dplyr::mutate(
    Season_Start_Year = ifelse(MONTH %in% c(1:8), YEAR - 1, YEAR)
  ) |>
  dplyr::group_by(Season_Start_Year) |>
  dplyr::summarize(
    DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE),
    Months_Count = dplyr::n()
  ) |>
  dplyr::rename(YEAR = Season_Start_Year) |>
  dplyr::mutate(INDICATOR_NAME = "gulf_stream_index")

## Fall AMO ----
fall_amo <- read.csv(here::here('01_inputs/unsmoothed_amo.csv')) |>
  dplyr::filter(Year >= 1970) |>
  dplyr::filter(Month %in% 4:9) |>
  dplyr::group_by(Year) |>
  dplyr::summarize(DATA_VALUE = mean(Value, na.rm = TRUE)) |>
  dplyr::rename(YEAR = Year) |>
  dplyr::mutate(INDICATOR_NAME = "fall_amo")

## Spring AMO ----
spring_amo <- read.csv(here::here('01_inputs/unsmoothed_amo.csv')) |>
  dplyr::filter(Year >= 1970) |>
  dplyr::filter(Month %in% c(9, 10, 11, 12, 1, 2)) |>
  dplyr::mutate(
    Season_Start_Year = ifelse(Month %in% c(1, 2), Year - 1, Year)
  ) |>
  dplyr::group_by(Season_Start_Year) |>
  dplyr::summarize(
    DATA_VALUE = mean(Value, na.rm = TRUE),
    Months_Count = dplyr::n()
  ) |> # keeps track of how many months went into the average
  dplyr::rename(YEAR = Season_Start_Year) |>
  dplyr::mutate(INDICATOR_NAME = "spring_amo")

## Condition (from NEesp2::species_condition) ----
# data comes from NEFSC survey data generated by survdat::get_survdat_data(channel, getBio = TRUE, getLengths = TRUE)

# channel <- dbutils::connect_to_database(
#   server = "server",
#   uid = "uid"
# )

# data <- survdat::get_survdat_data(
#   channel,
#   getBio = TRUE,
#   getLengths = TRUE
# )

condition <- NEesp2::species_condition <- function(
  data = data$survdat,
  LWparams = NEesp2::LWparams,
  species.codes = NEesp2::species.codes,
  by_EPU = TRUE,
  by_sex = FALSE,
  length_break = NULL,
  more_than_20_years = TRUE,
  record_outliers = FALSE,
  output = "soe"
) {
  # Condition pull stored in '03_outputs/plaice_condition.csv'
  ###################################################

  # Analyses ----

  ## Average price per pound ----
  avgprice <- com_data |>
    dplyr::filter(INDICATOR_NAME == "AVGPRICE_AMERICANPLAICE_2025_DOLlb")
}

NEesp2::plt_indicator(data = avgprice, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Total commercial landings (lbs) ----
landings <- com_data |>
  dplyr::filter(INDICATOR_NAME == "Commercial_AMERICANPLAICE_Landings_LBS")

NEesp2::plt_indicator(data = landings, ar = 1 / 4, include_trends = FALSE) +
  ggplot2::geom_smooth(
    method = "lm",
    se = FALSE,
    color = "purple",
    linetype = "solid"
  ) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::scale_y_continuous(labels = scales::label_scientific()) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Total commercial revenue ($USD/2025) ----
totalrev <- com_data |>
  dplyr::filter(INDICATOR_NAME == "TOTALANNUALREV_AMERICANPLAICE_2025Dols")

NEesp2::plt_indicator(data = totalrev, ar = 1 / 4, include_trends = FALSE) +
  ggplot2::geom_smooth(
    method = "lm",
    se = FALSE,
    color = "purple",
    linetype = "solid"
  ) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::scale_y_continuous(labels = scales::label_scientific()) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## N vessels ----
nvessels <- com_data |>
  dplyr::filter(INDICATOR_NAME == "N_Commercial_Vessels_Landing_AMERICANPLAICE")

NEesp2::plt_indicator(data = nvessels, ar = 1 / 4, include_trends = FALSE) +
  ggplot2::geom_smooth(
    method = "lm",
    se = FALSE,
    color = "purple",
    linetype = "solid"
  ) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Average revenue per vessel ($USD/2025) ----
vesselrev <- com_data |>
  dplyr::filter(INDICATOR_NAME == "AVGVESREVperYr_AMERICANPLAICE_2025_DOLlb")

NEesp2::plt_indicator(data = vesselrev, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::scale_y_continuous(labels = scales::label_scientific()) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Seasonal bottom temperature (Mar-Aug) ----
seasonal_bt <- bt_data |>
  dplyr::filter(YEAR %in% 1970:2025) |>
  dplyr::filter(MONTH %in% 3:8) |>
  dplyr::group_by(YEAR) |>
  dplyr::summarize(DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE)) |>
  dplyr::mutate(INDICATOR_NAME = "seasonal_bt")

NEesp2::plt_indicator(data = seasonal_bt, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Annual BT prior to fall survey (Sept-Aug) ----
fall_bt <- bt_data |>
  dplyr::filter(YEAR %in% 1970:2025) |>
  dplyr::group_by(YEAR) |>
  dplyr::mutate(
    Season_Start_Year = ifelse(MONTH %in% c(1:8), YEAR - 1, YEAR)
  ) |>
  dplyr::ungroup() |>
  dplyr::group_by(Season_Start_Year) |>
  dplyr::summarize(
    DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE),
    Days_Count = dplyr::n()
  ) |> #daily value, how many days are included in the average
  dplyr::rename(YEAR = Season_Start_Year) |>
  dplyr::mutate(INDICATOR_NAME = "fall_bt")

NEesp2::plt_indicator(data = fall_bt, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Annual BT prior to spring survey (Mar-Feb) ----
spring_bt <- bt_data |>
  dplyr::filter(YEAR %in% 1970:2025) |>
  dplyr::group_by(YEAR) |>
  dplyr::mutate(
    Season_Start_Year = ifelse(MONTH %in% c(1:2), YEAR - 1, YEAR)
  ) |>
  dplyr::ungroup() |>
  dplyr::group_by(Season_Start_Year) |>
  dplyr::summarize(
    DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE),
    Days_Count = dplyr::n()
  ) |> #daily value, how many days are included in the average
  dplyr::rename(YEAR = Season_Start_Year) |>
  dplyr::mutate(INDICATOR_NAME = "spring_bt")

NEesp2::plt_indicator(data = spring_bt, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Seasonal SST (Mar-June) ----
NEesp2::plt_indicator(data = seasonal_sst, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2026)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Gulf Stream Index ----
NEesp2::plt_indicator(data = gsi, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2025)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## AMO 6 months prior to Fall Survey (Apr-Sep) ----
NEesp2::plt_indicator(data = fall_amo, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2022)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## AMO 6 months prior to Spring Survey (Sept-Feb) ----
NEesp2::plt_indicator(data = spring_amo, ar = 1 / 4, include_trends = TRUE) +
  ggplot2::scale_x_continuous(
    breaks = c(seq(1970, 2020, by = 10), 2022)
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  )

## Species Condition ----
data <- read.csv(here::here("03_outputs/plaice_condition.csv")) |>
  dplyr::group_by(Species, YEAR, INDICATOR_NAME) |>
  dplyr::summarise(
    DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE),
    .groups = "drop"
  ) |>
  dplyr::mutate(EPU = "ALL")

NEesp2::plot_condition(data = data, var = "American plaice", return = TRUE) +
  # ggplot2::facet_wrap(~EPU, ncol = 1) +
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::ylab("Relative Condition") +
  ggplot2::theme(
    panel.border = ggplot2::element_rect(
      color = "black",
      fill = NA,
      linewidth = 1
    )
  )
